package springboot.bg.harisauto.user.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Country.java - Enum representing countries with their names and ISO codes.
 *
 * @author Kristian Popov
 */
@Getter
@AllArgsConstructor
public enum Country {
  AFGHANISTAN("Afghanistan", "AF", "AFG"),
  ALBANIA("Albania", "AL", "ALB"),
  ALGERIA("Algeria", "DZ", "DZA"),
  ANDORRA("Andorra", "AD", "AND"),
  ANGOLA("Angola", "AO", "AGO"),
  ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "AG", "ATG"),
  ARGENTINA("Argentina", "AR", "ARG"),
  ARMENIA("Armenia", "AM", "ARM"),
  AUSTRALIA("Australia", "AU", "AUS"),
  AUSTRIA("Austria", "AT", "AUT"),
  AZERBAIJAN("Azerbaijan", "AZ", "AZE"),
  BAHAMAS("Bahamas", "BS", "BHS"),
  BAHRAIN("Bahrain", "BH", "BHR"),
  BANGLADESH("Bangladesh", "BD", "BGD"),
  BARBADOS("Barbados", "BB", "BRB"),
  BELARUS("Belarus", "BY", "BLR"),
  BELGIUM("Belgium", "BE", "BEL"),
  BELIZE("Belize", "BZ", "BLZ"),
  BENIN("Benin", "BJ", "BEN"),
  BHUTAN("Bhutan", "BT", "BTN"),
  BOLIVIA("Bolivia", "BO", "BOL"),
  BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "BA", "BIH"),
  BOTSWANA("Botswana", "BW", "BWA"),
  BRAZIL("Brazil", "BR", "BRA"),
  BRUNEI("Brunei", "BN", "BRN"),
  BULGARIA("Bulgaria", "BG", "BGR"),
  BURKINA_FASO("Burkina Faso", "BF", "BFA"),
  BURUNDI("Burundi", "BI", "BDI"),
  CABO_VERDE("Cabo Verde", "CV", "CPV"),
  CAMBODIA("Cambodia", "KH", "KHM"),
  CAMEROON("Cameroon", "CM", "CMR"),
  CANADA("Canada", "CA", "CAN"),
  CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "CF", "CAF"),
  CHAD("Chad", "TD", "TCD"),
  CHILE("Chile", "CL", "CHL"),
  CHINA("China", "CN", "CHN"),
  COLOMBIA("Colombia", "CO", "COL"),
  COMOROS("Comoros", "KM", "COM"),
  CONGO_BRAZZAVILLE("Congo (Brazzaville)", "CG", "COG"),
  CONGO_KINSHASA("Congo (Kinshasa)", "CD", "COD"),
  COSTA_RICA("Costa Rica", "CR", "CRI"),
  COTE_D_IVOIRE("Côte d'Ivoire", "CI", "CIV"),
  CROATIA("Croatia", "HR", "HRV"),
  CUBA("Cuba", "CU", "CUB"),
  CYPRUS("Cyprus", "CY", "CYP"),
  CZECHIA("Czechia", "CZ", "CZE"),
  DENMARK("Denmark", "DK", "DNK"),
  DJIBOUTI("Djibouti", "DJ", "DJI"),
  DOMINICA("Dominica", "DM", "DMA"),
  DOMINICAN_REPUBLIC("Dominican Republic", "DO", "DOM"),
  ECUADOR("Ecuador", "EC", "ECU"),
  EGYPT("Egypt", "EG", "EGY"),
  EL_SALVADOR("El Salvador", "SV", "SLV"),
  EQUATORIAL_GUINEA("Equatorial Guinea", "GQ", "GNQ"),
  ERITREA("Eritrea", "ER", "ERI"),
  ESTONIA("Estonia", "EE", "EST"),
  ESWATINI("Eswatini", "SZ", "SWZ"),
  ETHIOPIA("Ethiopia", "ET", "ETH"),
  FIJI("Fiji", "FJ", "FJI"),
  FINLAND("Finland", "FI", "FIN"),
  FRANCE("France", "FR", "FRA"),
  GABON("Gabon", "GA", "GAB"),
  GAMBIA("Gambia", "GM", "GMB"),
  GEORGIA("Georgia", "GE", "GEO"),
  GERMANY("Germany", "DE", "DEU"),
  GHANA("Ghana", "GH", "GHA"),
  GREECE("Greece", "GR", "GRC"),
  GRENADA("Grenada", "GD", "GRD"),
  GUATEMALA("Guatemala", "GT", "GTM"),
  GUINEA("Guinea", "GN", "GIN"),
  GUINEA_BISSAU("Guinea-Bissau", "GW", "GNB"),
  GUYANA("Guyana", "GY", "GUY"),
  HAITI("Haiti", "HT", "HTI"),
  HONDURAS("Honduras", "HN", "HND"),
  HUNGARY("Hungary", "HU", "HUN"),
  ICELAND("Iceland", "IS", "ISL"),
  INDIA("India", "IN", "IND"),
  INDONESIA("Indonesia", "ID", "IDN"),
  IRAN("Iran", "IR", "IRN"),
  IRAQ("Iraq", "IQ", "IRQ"),
  IRELAND("Ireland", "IE", "IRL"),
  ISRAEL("Israel", "IL", "ISR"),
  ITALY("Italy", "IT", "ITA"),
  JAMAICA("Jamaica", "JM", "JAM"),
  JAPAN("Japan", "JP", "JPN"),
  JORDAN("Jordan", "JO", "JOR"),
  KAZAKHSTAN("Kazakhstan", "KZ", "KAZ"),
  KENYA("Kenya", "KE", "KEN"),
  KIRIBATI("Kiribati", "KI", "KIR"),
  KOREA_NORTH("North Korea", "KP", "PRK"),
  KOREA_SOUTH("South Korea", "KR", "KOR"),
  KOSOVO("Kosovo", "XK", "XKX"),
  KUWAIT("Kuwait", "KW", "KWT"),
  KYRGYZSTAN("Kyrgyzstan", "KG", "KGZ"),
  LAOS("Laos", "LA", "LAO"),
  LATVIA("Latvia", "LV", "LVA"),
  LEBANON("Lebanon", "LB", "LBN"),
  LESOTHO("Lesotho", "LS", "LSO"),
  LIBERIA("Liberia", "LR", "LBR"),
  LIBYA("Libya", "LY", "LBY"),
  LIECHTENSTEIN("Liechtenstein", "LI", "LIE"),
  LITHUANIA("Lithuania", "LT", "LTU"),
  LUXEMBOURG("Luxembourg", "LU", "LUX"),
  MADAGASCAR("Madagascar", "MG", "MDG"),
  MALAWI("Malawi", "MW", "MWI"),
  MALAYSIA("Malaysia", "MY", "MYS"),
  MALDIVES("Maldives", "MV", "MDV"),
  MALI("Mali", "ML", "MLI"),
  MALTA("Malta", "MT", "MLT"),
  MARSHALL_ISLANDS("Marshall Islands", "MH", "MHL"),
  MAURITANIA("Mauritania", "MR", "MRT"),
  MAURITIUS("Mauritius", "MU", "MUS"),
  MEXICO("Mexico", "MX", "MEX"),
  MICRONESIA("Micronesia", "FM", "FSM"),
  MOLDOVA("Moldova", "MD", "MDA"),
  MONACO("Monaco", "MC", "MCO"),
  MONGOLIA("Mongolia", "MN", "MNG"),
  MONTENEGRO("Montenegro", "ME", "MNE"),
  MOROCCO("Morocco", "MA", "MAR"),
  MOZAMBIQUE("Mozambique", "MZ", "MOZ"),
  MYANMAR("Myanmar", "MM", "MMR"),
  NAMIBIA("Namibia", "NA", "NAM"),
  NAURU("Nauru", "NR", "NRU"),
  NEPAL("Nepal", "NP", "NPL"),
  NETHERLANDS("Netherlands", "NL", "NLD"),
  NEW_ZEALAND("New Zealand", "NZ", "NZL"),
  NICARAGUA("Nicaragua", "NI", "NIC"),
  NIGER("Niger", "NE", "NER"),
  NIGERIA("Nigeria", "NG", "NGA"),
  NORTH_MACEDONIA("North Macedonia", "MK", "MKD"),
  NORWAY("Norway", "NO", "NOR"),
  OMAN("Oman", "OM", "OMN"),
  PAKISTAN("Pakistan", "PK", "PAK"),
  PALAU("Palau", "PW", "PLW"),
  PALESTINE("Palestine", "PS", "PSE"),
  PANAMA("Panama", "PA", "PAN"),
  PAPUA_NEW_GUINEA("Papua New Guinea", "PG", "PNG"),
  PARAGUAY("Paraguay", "PY", "PRY"),
  PERU("Peru", "PE", "PER"),
  PHILIPPINES("Philippines", "PH", "PHL"),
  POLAND("Poland", "PL", "POL"),
  PORTUGAL("Portugal", "PT", "PRT"),
  QATAR("Qatar", "QA", "QAT"),
  ROMANIA("Romania", "RO", "ROU"),
  RUSSIA("Russia", "RU", "RUS"),
  RWANDA("Rwanda", "RW", "RWA"),
  SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "KN", "KNA"),
  SAINT_LUCIA("Saint Lucia", "LC", "LCA"),
  SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", "VC", "VCT"),
  SAMOA("Samoa", "WS", "WSM"),
  SAN_MARINO("San Marino", "SM", "SMR"),
  SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "ST", "STP"),
  SAUDI_ARABIA("Saudi Arabia", "SA", "SAU"),
  SENEGAL("Senegal", "SN", "SEN"),
  SERBIA("Serbia", "RS", "SRB"),
  SEYCHELLES("Seychelles", "SC", "SYC"),
  SIERRA_LEONE("Sierra Leone", "SL", "SLE"),
  SINGAPORE("Singapore", "SG", "SGP"),
  SLOVAKIA("Slovakia", "SK", "SVK"),
  SLOVENIA("Slovenia", "SI", "SVN"),
  SOLOMON_ISLANDS("Solomon Islands", "SB", "SLB"),
  SOMALIA("Somalia", "SO", "SOM"),
  SOUTH_AFRICA("South Africa", "ZA", "ZAF"),
  SOUTH_SUDAN("South Sudan", "SS", "SSD"),
  SPAIN("Spain", "ES", "ESP"),
  SRI_LANKA("Sri Lanka", "LK", "LKA"),
  SUDAN("Sudan", "SD", "SDN"),
  SURINAME("Suriname", "SR", "SUR"),
  SWEDEN("Sweden", "SE", "SWE"),
  SWITZERLAND("Switzerland", "CH", "CHE"),
  SYRIA("Syria", "SY", "SYR"),
  TAIWAN("Taiwan", "TW", "TWN"),
  TAJIKISTAN("Tajikistan", "TJ", "TJK"),
  TANZANIA("Tanzania", "TZ", "TZA"),
  THAILAND("Thailand", "TH", "THA"),
  TIMOR_LESTE("Timor-Leste", "TL", "TLS"),
  TOGO("Togo", "TG", "TGO"),
  TONGA("Tonga", "TO", "TON"),
  TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "TT", "TTO"),
  TUNISIA("Tunisia", "TN", "TUN"),
  TURKEY("Turkey", "TR", "TUR"),
  TURKMENISTAN("Turkmenistan", "TM", "TKM"),
  TUVALU("Tuvalu", "TV", "TUV"),
  UGANDA("Uganda", "UG", "UGA"),
  UKRAINE("Ukraine", "UA", "UKR"),
  UNITED_ARAB_EMIRATES("United Arab Emirates", "AE", "ARE"),
  UNITED_KINGDOM("United Kingdom", "GB", "GBR"),
  UNITED_STATES("United States", "US", "USA"),
  URUGUAY("Uruguay", "UY", "URY"),
  UZBEKISTAN("Uzbekistan", "UZ", "UZB"),
  VANUATU("Vanuatu", "VU", "VUT"),
  VATICAN_CITY("Vatican City", "VA", "VAT"),
  VENEZUELA("Venezuela", "VE", "VEN"),
  VIETNAM("Vietnam", "VN", "VNM"),
  YEMEN("Yemen", "YE", "YEM"),
  ZAMBIA("Zambia", "ZM", "ZMB"),
  ZIMBABWE("Zimbabwe", "ZW", "ZWE");

  private final String name;
  private final String alpha2Code;
  private final String alpha3Code;
}
